// <auto-generated />
using System;
using HRMS.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HRMS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260827070414_TrendStatusBinaryEquipmentLevel")]
    partial class TrendStatusBinaryEquipmentLevel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HRMS.Modules.Auth.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanEmergencyStop")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HRMS.Modules.Equipment.Models.Compressor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlarmStatus")
                        .HasColumnType("integer");

                    b.Property<int>("CommunicationStatus")
                        .HasColumnType("integer");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("integer");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("MacAddress")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.ToTable("Compressors");
                });

            modelBuilder.Entity("HRMS.Modules.Equipment.Models.CompressorChannelSetting", b =>
                {
                    b.Property<int>("CompressorId")
                        .HasColumnType("integer");

                    b.Property<int>("ChannelNo")
                        .HasColumnType("integer");

                    b.Property<int?>("AlarmClearDelaySeconds")
                        .HasColumnType("integer");

                    b.Property<int?>("AlarmDelaySeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("AlarmEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("DecimalPlaces")
                        .HasColumnType("integer");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<short?>("LowerLimit")
                        .HasColumnType("smallint");

                    b.Property<short?>("UpperLimit")
                        .HasColumnType("smallint");

                    b.HasKey("CompressorId", "ChannelNo");

                    b.ToTable("CompressorChannelSettings");
                });

            modelBuilder.Entity("HRMS.Modules.Equipment.Models.CompressorSensorCurrent", b =>
                {
                    b.Property<int>("CompressorId")
                        .HasColumnType("integer");

                    b.Property<int>("ChannelNo")
                        .HasColumnType("integer");

                    b.Property<int>("AlarmStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("MeasuredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PendingSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Value")
                        .HasColumnType("smallint");

                    b.HasKey("CompressorId", "ChannelNo");

                    b.ToTable("CompressorSensorCurrents");
                });

            modelBuilder.Entity("HRMS.Modules.Equipment.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlarmStatus")
                        .HasColumnType("integer");

                    b.Property<string>("BuildingName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("ChargeAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("CommunicationStatus")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CompressorCapacity")
                        .HasColumnType("numeric");

                    b.Property<string>("CompressorType")
                        .HasColumnType("text");

                    b.Property<decimal?>("CoolingTowerCapacity")
                        .HasColumnType("numeric");

                    b.Property<string>("CoolingTowerType")
                        .HasColumnType("text");

                    b.Property<decimal?>("HighPressureTestPressure")
                        .HasColumnType("numeric");

                    b.Property<DateOnly?>("InstallDate")
                        .HasColumnType("date");

                    b.Property<string>("KgsManagementNumber")
                        .HasColumnType("text");

                    b.Property<decimal?>("LegalRefrigerationCapacity")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LowPressureTestPressure")
                        .HasColumnType("numeric");

                    b.Property<DateOnly?>("ManufactureDate")
                        .HasColumnType("date");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text");

                    b.Property<string>("ModelName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("OverPressureCutoff")
                        .HasColumnType("numeric");

                    b.Property<string>("PermitNumber")
                        .HasColumnType("text");

                    b.Property<decimal?>("RatedPower")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RatedVoltage")
                        .HasColumnType("numeric");

                    b.Property<string>("Refrigerant")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short?>("RunningCurrentThreshold")
                        .HasColumnType("smallint");

                    b.Property<int>("RunningStatus")
                        .HasColumnType("integer");

                    b.Property<decimal?>("SafetyValveSetPointCondenser")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SafetyValveSetPointEvaporator")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal?>("UsRefrigerationCapacity")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BuildingName", "Name")
                        .IsUnique();

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("HRMS.Modules.Logging.Models.EventLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EventLogs");
                });

            modelBuilder.Entity("HRMS.Modules.Trend.Models.CompressorMeasurement", b =>
                {
                    b.Property<int>("CompressorId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("MeasuredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short?>("Ch01")
                        .HasColumnType("smallint");

                    b.Property<short?>("Ch02")
                        .HasColumnType("smallint");

                    b.Property<short?>("Ch03")
                        .HasColumnType("smallint");

                    b.Property<short?>("Ch04")
                        .HasColumnType("smallint");

                    b.Property<short?>("Ch05")
                        .HasColumnType("smallint");

                    b.Property<short?>("Ch06")
                        .HasColumnType("smallint");

                    b.Property<short?>("Ch07")
                        .HasColumnType("smallint");

                    b.Property<bool>("HasAlarm")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("boolean");

                    b.Property<int>("RunningStatus")
                        .HasColumnType("integer");

                    b.HasKey("CompressorId", "MeasuredAt");

                    b.ToTable("CompressorMeasurements");
                });

            modelBuilder.Entity("HRMS.Modules.Equipment.Models.Compressor", b =>
                {
                    b.HasOne("HRMS.Modules.Equipment.Models.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRMS.Modules.Equipment.Models.CompressorChannelSetting", b =>
                {
                    b.HasOne("HRMS.Modules.Equipment.Models.Compressor", null)
                        .WithMany()
                        .HasForeignKey("CompressorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRMS.Modules.Equipment.Models.CompressorSensorCurrent", b =>
                {
                    b.HasOne("HRMS.Modules.Equipment.Models.Compressor", null)
                        .WithMany()
                        .HasForeignKey("CompressorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRMS.Modules.Trend.Models.CompressorMeasurement", b =>
                {
                    b.HasOne("HRMS.Modules.Equipment.Models.Compressor", null)
                        .WithMany()
                        .HasForeignKey("CompressorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
