// <auto-generated />
using System;
using HRMS.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HRMS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260826004617_AddCompressor")]
    partial class AddCompressor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HRMS.Modules.Equipment.Models.Compressor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlarmStatus")
                        .HasColumnType("integer");

                    b.Property<int>("CommunicationStatus")
                        .HasColumnType("integer");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("integer");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MacAddress")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.ToTable("Compressors");
                });

            modelBuilder.Entity("HRMS.Modules.Equipment.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BuildingName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("ChargeAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CompressorCapacity")
                        .HasColumnType("numeric");

                    b.Property<string>("CompressorType")
                        .HasColumnType("text");

                    b.Property<decimal?>("CoolingTowerCapacity")
                        .HasColumnType("numeric");

                    b.Property<string>("CoolingTowerType")
                        .HasColumnType("text");

                    b.Property<decimal?>("HighPressureTestPressure")
                        .HasColumnType("numeric");

                    b.Property<DateOnly?>("InstallDate")
                        .HasColumnType("date");

                    b.Property<string>("KgsManagementNumber")
                        .HasColumnType("text");

                    b.Property<decimal?>("LegalRefrigerationCapacity")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LowPressureTestPressure")
                        .HasColumnType("numeric");

                    b.Property<DateOnly?>("ManufactureDate")
                        .HasColumnType("date");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text");

                    b.Property<string>("ModelName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("OverPressureCutoff")
                        .HasColumnType("numeric");

                    b.Property<string>("PermitNumber")
                        .HasColumnType("text");

                    b.Property<decimal?>("RatedPower")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RatedVoltage")
                        .HasColumnType("numeric");

                    b.Property<string>("Refrigerant")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("RunningCurrentThreshold")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SafetyValveSetPointCondenser")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SafetyValveSetPointEvaporator")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal?>("UsRefrigerationCapacity")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BuildingName", "Name")
                        .IsUnique();

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("HRMS.Modules.Equipment.Models.Compressor", b =>
                {
                    b.HasOne("HRMS.Modules.Equipment.Models.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
