// <auto-generated />
using System;
using HRMS.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HRMS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HRMS.Modules.Attachment.Models.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<int>("OwnerType")
                        .HasColumnType("integer");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Slot")
                        .HasColumnType("text");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("UploadedByUserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerType", "OwnerId");

                    b.HasIndex("OwnerType", "OwnerId", "Slot")
                        .IsUnique()
                        .HasFilter("\"Slot\" IS NOT NULL");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("HRMS.Modules.Auth.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BackupPersonName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAppointed")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("LegalTrainingDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NextTrainingDate")
                        .HasColumnType("date");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone1")
                        .HasColumnType("text");

                    b.Property<string>("Phone2")
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HRMS.Modules.Auth.Models.UserEquipment", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("UserEquipments");
                });

            modelBuilder.Entity("HRMS.Modules.Equipment.Models.Compressor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlarmStatus")
                        .HasColumnType("integer");

                    b.Property<int>("CommunicationStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DisconnectedSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("integer");

                    b.Property<bool>("HasCommunicationAlarm")
                        .HasColumnType("boolean");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("MacAddress")
                        .HasColumnType("text");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.ToTable("Compressors");
                });

            modelBuilder.Entity("HRMS.Modules.Equipment.Models.CompressorChannelSetting", b =>
                {
                    b.Property<int>("CompressorId")
                        .HasColumnType("integer");

                    b.Property<int>("ChannelNo")
                        .HasColumnType("integer");

                    b.Property<int?>("AlarmClearDelaySeconds")
                        .HasColumnType("integer");

                    b.Property<int?>("AlarmDelaySeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("AlarmEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DecimalPlaces")
                        .HasColumnType("integer");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<short?>("LowerLimit")
                        .HasColumnType("smallint");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short?>("UpperLimit")
                        .HasColumnType("smallint");

                    b.HasKey("CompressorId", "ChannelNo");

                    b.ToTable("CompressorChannelSettings");
                });

            modelBuilder.Entity("HRMS.Modules.Equipment.Models.CompressorSensorCurrent", b =>
                {
                    b.Property<int>("CompressorId")
                        .HasColumnType("integer");

                    b.Property<int>("ChannelNo")
                        .HasColumnType("integer");

                    b.Property<int>("AlarmStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("MeasuredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PendingSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Value")
                        .HasColumnType("smallint");

                    b.HasKey("CompressorId", "ChannelNo");

                    b.ToTable("CompressorSensorCurrents");
                });

            modelBuilder.Entity("HRMS.Modules.Equipment.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlarmStatus")
                        .HasColumnType("integer");

                    b.Property<decimal?>("BrineInletMax")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BrineInletMin")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BrineOutletMax")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BrineOutletMin")
                        .HasColumnType("numeric");

                    b.Property<string>("BuildingName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BuildingNumber")
                        .HasColumnType("text");

                    b.Property<decimal?>("ChargeAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("CommunicationStatus")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CompressorCapacity")
                        .HasColumnType("numeric");

                    b.Property<int?>("CompressorCount")
                        .HasColumnType("integer");

                    b.Property<string>("CompressorManufacturer")
                        .HasColumnType("text");

                    b.Property<string>("CompressorType")
                        .HasColumnType("text");

                    b.Property<string>("CondenserType")
                        .HasColumnType("text");

                    b.Property<decimal?>("CoolingTowerCapacity")
                        .HasColumnType("numeric");

                    b.Property<int?>("CoolingTowerCount")
                        .HasColumnType("integer");

                    b.Property<string>("CoolingTowerManufacturer")
                        .HasColumnType("text");

                    b.Property<string>("CoolingTowerType")
                        .HasColumnType("text");

                    b.Property<decimal?>("CoolingWaterInletMax")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CoolingWaterInletMin")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CoolingWaterOutletMax")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CoolingWaterOutletMin")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DesignPressure")
                        .HasColumnType("numeric");

                    b.Property<string>("EvaporatorType")
                        .HasColumnType("text");

                    b.Property<bool>("HasBrine")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasCoolingWater")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasVoltage")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("LegalRefrigerationCapacity")
                        .HasColumnType("numeric");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("ManagementNumber")
                        .HasColumnType("text");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text");

                    b.Property<string>("ModelName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal?>("OverPressureCutoff")
                        .HasColumnType("numeric");

                    b.Property<string>("PermitNumber")
                        .HasColumnType("text");

                    b.Property<decimal?>("RatedCurrent")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RatedVoltage")
                        .HasColumnType("numeric");

                    b.Property<string>("Refrigerant")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short?>("RunningCurrentThreshold")
                        .HasColumnType("smallint");

                    b.Property<string>("SafetyValve")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal?>("UsRefrigerationCapacity")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("VoltageMax")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("VoltageMin")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BuildingName", "Name")
                        .IsUnique();

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("HRMS.Modules.EquipmentInspectionHistory.Models.EquipmentInspectionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedByUserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.ToTable("EquipmentInspectionHistories");
                });

            modelBuilder.Entity("HRMS.Modules.InspectionReport.Models.InspectionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("Level1ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Level1ApproverId")
                        .HasColumnType("integer");

                    b.Property<string>("Level1ApproverName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Level2ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Level2ApproverId")
                        .HasColumnType("integer");

                    b.Property<string>("Level2ApproverName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Level3ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Level3ApproverId")
                        .HasColumnType("integer");

                    b.Property<string>("Level3ApproverName")
                        .HasColumnType("text");

                    b.Property<string>("Opinion")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId", "WeekStartDate")
                        .IsUnique();

                    b.ToTable("InspectionLogs");
                });

            modelBuilder.Entity("HRMS.Modules.InspectionReport.Models.InspectionResult", b =>
                {
                    b.Property<int>("LogId")
                        .HasColumnType("integer");

                    b.Property<string>("ItemNo")
                        .HasColumnType("text");

                    b.Property<string>("Fri")
                        .HasColumnType("text");

                    b.Property<string>("Memo")
                        .HasColumnType("text");

                    b.Property<string>("Mon")
                        .HasColumnType("text");

                    b.Property<string>("Sat")
                        .HasColumnType("text");

                    b.Property<string>("Sun")
                        .HasColumnType("text");

                    b.Property<string>("Thu")
                        .HasColumnType("text");

                    b.Property<string>("Tue")
                        .HasColumnType("text");

                    b.Property<string>("Wed")
                        .HasColumnType("text");

                    b.HasKey("LogId", "ItemNo");

                    b.ToTable("InspectionResults");
                });

            modelBuilder.Entity("HRMS.Modules.Logging.Models.EventLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<int?>("ChannelNo")
                        .HasColumnType("integer");

                    b.Property<int?>("CompressorId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DecimalPlaces")
                        .HasColumnType("integer");

                    b.Property<int?>("EquipmentId")
                        .HasColumnType("integer");

                    b.Property<short?>("LowerLimit")
                        .HasColumnType("smallint");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.Property<short?>("UpperLimit")
                        .HasColumnType("smallint");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.Property<short?>("Value")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("EventLogs");
                });

            modelBuilder.Entity("HRMS.Modules.Notice.Models.Notice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedByUserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Notices");
                });

            modelBuilder.Entity("HRMS.Modules.OperationReport.Models.OperationItemValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompressorId")
                        .HasColumnType("integer");

                    b.Property<string>("ItemKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LogId")
                        .HasColumnType("integer");

                    b.Property<string>("Time0900")
                        .HasColumnType("text");

                    b.Property<string>("Time1300")
                        .HasColumnType("text");

                    b.Property<string>("Time1600")
                        .HasColumnType("text");

                    b.Property<string>("Time2100")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompressorId");

                    b.HasIndex("LogId", "ItemKey", "CompressorId");

                    b.ToTable("OperationItemValues");
                });

            modelBuilder.Entity("HRMS.Modules.OperationReport.Models.OperationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("Level1ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Level1ApproverId")
                        .HasColumnType("integer");

                    b.Property<string>("Level1ApproverName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Level2ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Level2ApproverId")
                        .HasColumnType("integer");

                    b.Property<string>("Level2ApproverName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Level3ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Level3ApproverId")
                        .HasColumnType("integer");

                    b.Property<string>("Level3ApproverName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId", "Date")
                        .IsUnique();

                    b.ToTable("OperationLogs");
                });

            modelBuilder.Entity("HRMS.Modules.OperationReport.Models.OperationReferenceValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ItemKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LogId")
                        .HasColumnType("integer");

                    b.Property<string>("ReferenceText")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LogId", "ItemKey");

                    b.ToTable("OperationReferenceValues");
                });

            modelBuilder.Entity("HRMS.Modules.RepairLog.Models.RepairLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedByUserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("integer");

                    b.Property<string>("FailureCause")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Level1ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Level1ApproverId")
                        .HasColumnType("integer");

                    b.Property<string>("Level1ApproverName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Level2ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Level2ApproverId")
                        .HasColumnType("integer");

                    b.Property<string>("Level2ApproverName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Level3ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Level3ApproverId")
                        .HasColumnType("integer");

                    b.Property<string>("Level3ApproverName")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Opinion")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PerformedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PerformedBy")
                        .HasColumnType("text");

                    b.Property<string>("PreventiveAction")
                        .HasColumnType("text");

                    b.Property<string>("Result")
                        .HasColumnType("text");

                    b.Property<string>("StateAfter")
                        .HasColumnType("text");

                    b.Property<string>("StateBefore")
                        .HasColumnType("text");

                    b.Property<string>("Target")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.ToTable("RepairLogs");
                });

            modelBuilder.Entity("HRMS.Modules.TrainingLog.Models.TrainingLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Attendees")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedByUserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Instructor")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Level1ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Level1ApproverId")
                        .HasColumnType("integer");

                    b.Property<string>("Level1ApproverName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Level2ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Level2ApproverId")
                        .HasColumnType("integer");

                    b.Property<string>("Level2ApproverName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Level3ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Level3ApproverId")
                        .HasColumnType("integer");

                    b.Property<string>("Level3ApproverName")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PerformedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TrainingLogs");
                });

            modelBuilder.Entity("HRMS.Modules.Trend.Models.CompressorMeasurement", b =>
                {
                    b.Property<int>("CompressorId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("MeasuredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short?>("Ch01")
                        .HasColumnType("smallint");

                    b.Property<short?>("Ch02")
                        .HasColumnType("smallint");

                    b.Property<short?>("Ch03")
                        .HasColumnType("smallint");

                    b.Property<short?>("Ch04")
                        .HasColumnType("smallint");

                    b.Property<short?>("Ch05")
                        .HasColumnType("smallint");

                    b.Property<short?>("Ch06")
                        .HasColumnType("smallint");

                    b.Property<short?>("Ch07")
                        .HasColumnType("smallint");

                    b.Property<bool>("HasAlarm")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("boolean");

                    b.HasKey("CompressorId", "MeasuredAt");

                    b.ToTable("CompressorMeasurements");
                });

            modelBuilder.Entity("HRMS.Modules.Auth.Models.UserEquipment", b =>
                {
                    b.HasOne("HRMS.Modules.Equipment.Models.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMS.Modules.Auth.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRMS.Modules.Equipment.Models.Compressor", b =>
                {
                    b.HasOne("HRMS.Modules.Equipment.Models.Equipment", null)
                        .WithMany("Compressors")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRMS.Modules.Equipment.Models.CompressorChannelSetting", b =>
                {
                    b.HasOne("HRMS.Modules.Equipment.Models.Compressor", null)
                        .WithMany("ChannelSettings")
                        .HasForeignKey("CompressorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRMS.Modules.Equipment.Models.CompressorSensorCurrent", b =>
                {
                    b.HasOne("HRMS.Modules.Equipment.Models.Compressor", null)
                        .WithMany()
                        .HasForeignKey("CompressorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRMS.Modules.EquipmentInspectionHistory.Models.EquipmentInspectionHistory", b =>
                {
                    b.HasOne("HRMS.Modules.Equipment.Models.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRMS.Modules.InspectionReport.Models.InspectionLog", b =>
                {
                    b.HasOne("HRMS.Modules.Equipment.Models.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRMS.Modules.InspectionReport.Models.InspectionResult", b =>
                {
                    b.HasOne("HRMS.Modules.InspectionReport.Models.InspectionLog", null)
                        .WithMany("Results")
                        .HasForeignKey("LogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRMS.Modules.OperationReport.Models.OperationItemValue", b =>
                {
                    b.HasOne("HRMS.Modules.Equipment.Models.Compressor", null)
                        .WithMany()
                        .HasForeignKey("CompressorId");

                    b.HasOne("HRMS.Modules.OperationReport.Models.OperationLog", null)
                        .WithMany("Items")
                        .HasForeignKey("LogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRMS.Modules.OperationReport.Models.OperationLog", b =>
                {
                    b.HasOne("HRMS.Modules.Equipment.Models.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRMS.Modules.OperationReport.Models.OperationReferenceValue", b =>
                {
                    b.HasOne("HRMS.Modules.OperationReport.Models.OperationLog", null)
                        .WithMany("References")
                        .HasForeignKey("LogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRMS.Modules.RepairLog.Models.RepairLog", b =>
                {
                    b.HasOne("HRMS.Modules.Equipment.Models.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRMS.Modules.Trend.Models.CompressorMeasurement", b =>
                {
                    b.HasOne("HRMS.Modules.Equipment.Models.Compressor", null)
                        .WithMany()
                        .HasForeignKey("CompressorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRMS.Modules.Equipment.Models.Compressor", b =>
                {
                    b.Navigation("ChannelSettings");
                });

            modelBuilder.Entity("HRMS.Modules.Equipment.Models.Equipment", b =>
                {
                    b.Navigation("Compressors");
                });

            modelBuilder.Entity("HRMS.Modules.InspectionReport.Models.InspectionLog", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("HRMS.Modules.OperationReport.Models.OperationLog", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("References");
                });
#pragma warning restore 612, 618
        }
    }
}
